export const products = [
  {
    id: 1,
    title: "HAVIT HV-G92 Gamepad",
    image: "/images/pro1.jpeg",
    category: "Electronics",
    salePrice: 120,
    originalPrice: 160,
    rating: 4,
    ratedBy: 88,
    slug: "HAVIT-HV-G92-Gamepad",
    description: "The HAVIT HV-G92 Gamepad delivers superior gaming control with responsive buttons and ergonomic design, perfect for an immersive gaming experience on various devices.",
    size: ["S", "M", "L", 'XL'],
    color: ["Black", "Red"],
  },
  {
    id: 2,
    title: "AK-900 Wired Keyboard",
    image: "/images/pro2.jpeg",
    category: "Fashion",
    salePrice: 969,
    originalPrice: 1160,
    rating: 3,
    ratedBy: 75,
    slug: "AK-900-Wired-Keyboard",
    description: "The AK-900 Wired Keyboard offers a stylish design with smooth keypresses, making it a perfect companion for both work and play, built for comfort and reliability.",
    size: ["Full Size", "Compact"],
    color: ["Black", "White"],
  },
  {
    id: 3,
    title:  "IPS LCD Gaming Monitor",
    image: "/images/pro3.jpg",
    category: "Home Appliances",
    salePrice: 370,
    originalPrice: 400,
    rating: 5,
    ratedBy: 99,
    slug: "IPS-LCD-Gaming-Monitor",
    description: "Experience vivid colors and sharp details with the IPS LCD Gaming Monitor, designed for immersive gaming and smooth visuals, ideal for both casual and competitive players.",
    size: ["27 inch", "32 inch"],
    color: ["Black", "Silver"],
  },
  {
    id: 4,
    title: "S-Series Comfort Chair",
    image: "/images/pro4.webp",
    category: "Home Appliances",
    salePrice: 375,
    originalPrice: 400,
    rating: 4,
    ratedBy: 23,
    slug: "S-Series-Comfort-Chair",
    description: "Relax in style with the S-Series Comfort Chair, designed for ultimate comfort and ergonomic support. Perfect for long hours of gaming or work without sacrificing style.",
    size: ["S", "M", "L", 'XL'],
    color: ["Black", "Gray", "Blue"],
  },
  {
    id: 5,
    title: "RGB Liquid CPU Cooler",
    image: "/images/pro5.webp",
    category: "Home Appliances",
    salePrice: 199.99,
    originalPrice: 249.99,
    rating: 2,
    ratedBy: 65,
    slug: "RGB-liquid-CPU-Cooler",
    description: "Enhance your PC's performance and aesthetics with the RGB Liquid CPU Cooler. Keep your system cool during intense gaming sessions, while adding a customizable lighting effect.",
    size: ["120mm", "240mm", "360mm"],
    color: ["Black", "White"],
  },
  {
    id: 8,
    title: "Breed Dry Dog Food",
    image: "/images/p1.webp",
    category: "Home Appliances",
    salePrice: 199.99,
    originalPrice: 100,
    rating: 4.8,
    ratedBy: 35,
    slug: "Breed-Dry-Dog-Food",
    description: "Breed Dry Dog Food provides balanced nutrition and promotes healthy growth in dogs. With a mix of high-quality ingredients, it’s the ideal choice for your pet's health.",
    size: ["2kg", "5kg", "10kg"],
    color: ["Brown", "Beige"],
  },
  {
    id: 9,
    title: "CANON EOS DSLR Camera",
    image: "/images/p2.webp",
    category: "Home Appliances",
    salePrice: 199.99,
    originalPrice: 360,
    rating: 4.8,
    ratedBy: 90,
    slug: "CANON-EOS-DSLR-Camera",
    description: "Capture every moment in stunning detail with the CANON EOS DSLR Camera. With advanced features and easy usability, it’s perfect for both beginners and seasoned photographers.",
    size: ["S", "M", "L", 'XL'],
    color: ["Black"],
  },
  {
    id: 21,
    title: "Boxy Denim Jacket",
    image: "/images/p13.webp",
    category: "Home Appliances",
    salePrice: 199.99,
    originalPrice: 800,
    rating: 3,
    ratedBy: 30,
    slug: "Boxy-Denim-Jacket",
    description: "Stay on trend with the Boxy Denim Jacket, crafted from durable denim and designed with a boxy fit for a relaxed, stylish look that pairs well with any outfit.",
    size: ["S", "M", "L", "XL"],
    color: ["Blue", "Black"],
  },
  {
    id: 11,
    title: "Curology Product Set",
    image: "/images/p4.png",
    category: "Home Appliances",
    salePrice: 199.99,
    originalPrice: 500,
    rating: 4.8,
    ratedBy: 145,
    slug: "Curology-Product-Set",
    description: "Transform your skincare routine with the Curology Product Set. Featuring personalized formulas to address your unique skin needs, it’s a great solution for healthy, glowing skin.",
    size: ["S", "M", "L", 'XL'],
    color: ["White"],
  },
  {
    id: 12,
    title: "Kids Electric Car",
    image: "/images/p5.webp",
    category: "Home Appliances",
    salePrice: 199.99,
    originalPrice: 960,
    rating: 5,
    ratedBy: 65,
    slug: "Kids-Electric-Car",
    newArrival: true,
    description: "Let your child enjoy the thrill of driving with the Kids Electric Car. Built with safety features, this fun and interactive toy is perfect for hours of outdoor enjoyment.",
    size: ["S", "M", "L", 'XL'],
    color: ["Red", "Blue", "Pink"],
  },
  {
    id: 13,
    title: "Jr. Zoom Soccer Cleats",
    image: "/images/p6.jpg",
    category: "Home Appliances",
    salePrice: 199.99,
    originalPrice: 1160,
    rating: 4.8,
    ratedBy: 35,
    slug: "Jr-Zoom-Soccer-Cleats",
    description: "Kick-start your child’s soccer career with Jr. Zoom Soccer Cleats. Designed for comfort, speed, and durability, they offer superior traction on the field for young athletes.",
    size: ["Youth 1", "Youth 2", "Youth 3"],
    color: ["Black", "White", "Blue"],
  },
  {
    id: 14,
    title: "GP11 Shooter USB Gamepad",
    image: "/images/p7.jpg",
    category: "Home Appliances",
    salePrice: 199.99,
    originalPrice: 660,
    rating: 4.8,
    ratedBy: 55,
    slug: "GP11-Shooter-USB-Gamepad",
    newArrival: true,
    description: "Elevate your gaming with the GP11 Shooter USB Gamepad. Designed for FPS games, it provides precise controls and a responsive feel for a competitive edge.",
    size: ["S", "M", "L", 'XL'],
    color: ["Black", "Red"],
  },
  {
    id: 15,
    title: "Quilted Satin Jacket",
    image: "/images/p8.webp",
    category: "Home Appliances",
    salePrice: 199.99,
    originalPrice: 600,
    rating: 4.8,
    ratedBy: 55,
    slug: "Quilted-Satin-Jacket",
    description: "The Quilted Satin Jacket blends style and warmth, making it the perfect addition to your wardrobe. Ideal for cool weather, it provides a sleek, fashionable look.",
    size: ["S", "M", "L"],
    color: ["Black", "Gray", "Navy"],
  },
  {
    id: 16,
    title:  "Diamond Printed Shirt (Slim / Modern Fit)",
    image: "/images/p9.webp",
    category: "Home Appliances",
    salePrice: 199.99,
    originalPrice: 249.99,
    rating: 4.8,
    ratedBy: 230,
    slug: "Diamond-Printed-Shirt",
    description: "Stand out in the Diamond Printed Shirt. Featuring a slim, modern fit and striking design, this shirt will add a unique touch to your casual or semi-formal outfits.",
    size: ["S", "M", "L", "XL"],
    color: ["Black", "White"],
  },
  {
    id: 18,
    title: "Blue Slim Denim Mens Jeans",
    image: "/images/p10.jpg",
    category: "Home Appliances",
    salePrice: 199.99,
    originalPrice: 319.99,
    rating: 4.8,
    ratedBy: 80,
    slug: "blue-slim-denim-mens-jeans",
    newArrival: true,
    description: "The Blue Slim Denim Men’s Jeans offer a sleek, modern look with a perfect fit. Made from durable denim, these jeans are designed for both comfort and style.",
    size: ["30", "32", "34", "36"],
    color: ["Blue"],
  },
  {
    id: 19,
    title: "JBL Over-Ear Wireless Headphones",
    image: "/images/p11.jpg",
    category: "Home Appliances",
    salePrice: 199.99,
    originalPrice: 660,
    rating: 4.8,
    ratedBy: 90,
    slug: "JBL-Over-Ear-Wireless-Headphones",
    description: "Enjoy superior sound quality and comfort with JBL Over-Ear Wireless Headphones. With a long-lasting battery and immersive audio, they’re ideal for music lovers and gamers alike.",
    size: ["S", "M", "L", 'XL'],
    color: ["Black", "White", "Blue"],
  },
  {
    id: 20,
    title: "Adjustable Gaming Chair",
    image: "/images/p12.webp",
    category: "Home Appliances",
    salePrice: 199.99,
    originalPrice: 799,
    rating: 4.8,
    ratedBy: 89,
    slug: "Adjustable-Gaming-Chair",
    description: "Elevate your gaming setup with the Adjustable Gaming Chair. Designed for ultimate comfort, it features adjustable armrests, a reclining backrest, and durable construction.",
    size: ["S", "M", "L", 'XL'],
    color: ["Black", "Red", "Blue"],
  },
];
export const bestSelling = [
  {
    id: 10,
    title: "The North Coat",
    image: "/images/pro6.jpeg",
    category: "Clothing",
    salePrice: 260,
    originalPrice: 360,
    rating: 4,
    ratedBy: 65,
    slug: "the-north-coat",
    description: "Experience ultimate warmth and comfort with The North Coat, designed for harsh winters and stylish outings.",
    color: ["Black", "Gray", "Navy Blue"],
    size: ["S", "M", "L", "XL"],
  },
  {
    id: 11,
    title: "Gucci Duffle Bag",
    image: "/images/pro7.webp",
    category: "Accessories",
    salePrice: 960,
    originalPrice: 1160,
    rating: 4.5,
    ratedBy: 88,
    slug: "gucci-duffle-bag",
    description: "A premium duffle bag by Gucci, perfect for travel and daily use, combining elegance with functionality.",
    color: ["Brown", "Black", "Beige"],
    size: ["One Size"],
  },
  {
    id: 12,
    title: "Small Bookshelf",
    image: "/images/pro9.webp",
    category: "Furniture",
    salePrice: 360,
    originalPrice: 570,
    rating: 3,
    ratedBy: 70,
    slug: "small-bookshelf",
    description: "Compact and stylish, this bookshelf is ideal for organizing your books and decor in smaller spaces.",
    color: ["Walnut", "White", "Black"],
    size: ["Small"],
  },
  {
    id: 13,
    title: "Street Style Graphic T-Shirt",
    image: "/images/pro8.webp",
    category: "Clothing",
    salePrice: 20,
    originalPrice: 160,
    rating: 4,
    ratedBy: 64,
    slug: "street-style-graphic-t-shirt",
    description: "Add a touch of urban flair to your wardrobe with this trendy graphic T-shirt, perfect for casual wear.",
    color: ["White", "Black", "Gray"],
    size: ["S", "M", "L", "XL"],
  },
];
