"use client";

export const products = [
  {
    id: 1,
    image: "/images/pro1.jpeg",
    category: "Electronics",
    salePrice: 120,
    originalPrice: 160,
    rating: 4,
    ratedBy: 88,
    slug: "HAVIT HV-G92 Gamepad",
  },
  {
    id: 2,
    image: "/images/pro2.jpeg",
    category: "Fashion",
    salePrice: 969,
    originalPrice: 1160,
    rating: 3,
    ratedBy: 75,
    slug: "AK-900 Wired Keyboard",
  },
  {
    id: 3,
    image: "/images/pro3.jpg",
    category: "Home Appliances",
    salePrice: 370,
    originalPrice: 400,
    rating: 5,
    ratedBy: 99,
    slug: "IPS LCD Gaming Monitor",
  },
  {
    id: 4,
    image: "/images/pro4.webp",
    category: "Home Appliances",
    salePrice: 375,
    originalPrice: 400,
    rating: 4,
    ratedBy: 23,
    slug: "S-Series Comfort Chair",
  },
  {
    id: 5,
    image: "/images/pro5.webp",
    category: "Home Appliances",
    salePrice: 199.99,
    originalPrice: 249.99,
    rating: 2,
    ratedBy: 65,
    slug: "RGB liquid CPU Cooler",
  },
  {
    id: 6,
    image: "/path/to/product3.jpg",
    category: "Home Appliances",
    salePrice: 199.99,
    originalPrice: 249.99,
    rating: 4.8,
    ratedBy: 230,
    slug: "product-3",
  },
  {
    id: 7,
    image: "/path/to/product3.jpg",
    category: "Home Appliances",
    salePrice: 199.99,
    originalPrice: 249.99,
    rating: 4.8,
    ratedBy: 230,
    slug: "product-3",
  },
  // new
  {
    id: 8,
    image: "/images/p1.webp",
    category: "Home Appliances",
    salePrice: 199.99,
    originalPrice: 100,
    rating: 4.8,
    ratedBy: 35,
    slug: "Breed Dry Dog Food",
  },
  {
    id: 9,
    image: "/images/p2.webp",
    category: "Home Appliances",
    salePrice: 199.99,
    originalPrice: 360,
    rating: 4.8,
    ratedBy: 90,
    slug: "CANON EOS DSLR Camera",
  },
  {
    id: 21,
    image: "/images/p13.webp",
    category: "Home Appliances",
    salePrice: 199.99,
    originalPrice: 800,
    rating: 3,
    ratedBy: 30,
    slug: "Boxy Denim Jacket",
  },
  {
    id: 11,
    image: "/images/p4.png",
    category: "Home Appliances",
    salePrice: 199.99,
    originalPrice: 500,
    rating: 4.8,
    ratedBy: 145,
    slug: "Curology Product Set",
  },
  {
    id: 12,
    image: "/images/p5.webp",
    category: "Home Appliances",
    salePrice: 199.99,
    originalPrice: 960,
    rating: 5,
    ratedBy: 65,
    slug: "Kids Electric Car",
    newArrival: true
  },
  {
    id: 13,
    image: "/images/p6.jpg",
    category: "Home Appliances",
    salePrice: 199.99,
    originalPrice: 1160,
    rating: 4.8,
    ratedBy: 35,
    slug: "Jr. Zoom Soccer Cleats",
  },
  {
    id: 14,
    image: "/images/p7.jpg",
    category: "Home Appliances",
    salePrice: 199.99,
    originalPrice: 660,
    rating: 4.8,
    ratedBy: 55,
    slug: "GP11 Shooter USB Gamepad",
    newArrival: true
  },
  {
    id: 15,
    image: "/images/p8.webp",
    category: "Home Appliances",
    salePrice: 199.99,
    originalPrice: 600,
    rating: 4.8,
    ratedBy: 55,
    slug: "Quilted Satin Jacket",
  },
  {
    id: 16,
    image: "/images/p9.webp",
    category: "Home Appliances",
    salePrice: 199.99,
    originalPrice: 249.99,
    rating: 4.8,
    ratedBy: 230,
    slug: "Diamond Printed Shirt (Slim / Modern Fit)",
  },
  {
    id: 18,
    image: "/images/p10.jpg",
    category: "Home Appliances",
    salePrice: 199.99,
    originalPrice: 319.99,
    rating: 4.8,
    ratedBy: 80,
    slug: "Blue Slim Denim Mens Jeans",
    newArrival: true
  },
  {
    id: 19,
    image: "/images/p11.jpg",
    category: "Home Appliances",
    salePrice: 199.99,
    originalPrice: 249.99,
    rating: 4.8,
    ratedBy: 230,
    slug: "ADIDAS RUNNING CAP",
  },
  {
    id: 20,
    image: "/images/p12.webp",
    category: "Home Appliances",
    salePrice: 79.99,
    originalPrice: 140,
    rating: 4.8,
    ratedBy: 230,
    slug: "Blue Tropical Print Super Soft Premium Cuban Collar",
  },
  {
    id: 10,
    image: "/images/p3.webp",
    category: "Home Appliances",
    salePrice: 199.99,
    originalPrice: 700,
    rating: 4.8,
    ratedBy: 325,
    slug: "ASUS FHD Gaming Laptop",
    newArrival: true
  },

];

export const bestSelling = [
    {
        id: 10,
        image: "/images/pro6.jpeg",
        category: "Electronics",
        salePrice: 260,
        originalPrice: 360,
        rating: 4,
        ratedBy: 65,
        slug: "The north coat",
      },
    {
        id: 11,
        image: "/images/pro7.webp",
        category: "Electronics",
        salePrice: 960,
        originalPrice: 1160,
        rating: 4.5,
        ratedBy: 88,
        slug: "Gucci duffle bag",
      },
    {
        id: 12,
        image: "/images/pro9.webp",
        category: "Electronics",
        salePrice: 360,
        originalPrice: 570,
        rating: 3,
        ratedBy: 70,
        slug: "Small BookSelf",
      },
    {
        id: 13,
        image: "/images/pro8.webp",
        category: "Electronics",
        salePrice: 20,
        originalPrice: 160,
        rating: 4,
        ratedBy: 64,
        slug: "Street Style Graphic T-Shirt",
      },
]